name: send-results-to-testrail
on: [workflow_dispatch]
env:
  TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
  TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
jobs:
  send-test-results-to-testrail:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Execute automated tests
      #   uses: ...
      - name: Python setup
        if: always()
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: TestRail CLI upload results
        if: always()
        run: |
          pip install trcli
          trcli -y \
            -h https://imdabtg.testrail.io/ \
            --project "AI Verify" \
            -u $TESTRAIL_USERNAME \
            -p $TESTRAIL_PASSWORD \
            parse_junit \
            --title "AI Verify" \
            --result-fields "os:Ubuntu 22.04" \
            --case-fields "refs:TEST-2" \
            --milestone-id "1" \
            --run-id "4" \
            --run-description ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -f "./test-results/junit-report.xml"
